# Generated by Django 5.2.6 on 2025-09-28 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(db_collation='utf8mb4_general_ci', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=64)),
                ('user_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('document_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_data', models.BinaryField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]+$', 'Invalid mobile number format')])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('address', models.TextField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters and spaces allowed')])),
                ('lastname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters and spaces allowed')])),
                ('dob', models.DateField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='api.employee')),
            ],
        ),
    ]
